name: atlas_protocol
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - ipython
  - pip
  - r-conflicted
  - r-docopt
  - r-readxl
  - bioconductor-singlecellexperiment
  - r-readr
  - r-stringr
  - r-ggplot2
  - pip:
      - scanpy
      - leidenalg
